# -*- coding: utf-8 -*-
"""website-rag-chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/165CrAYoDvn1-IZnBsOavpBUwFKYDILy7
"""

import os
import streamlit as st
from dotenv import load_dotenv
from langchain_community.document_loaders import CSVLoader,Docx2txtLoader,PyPDFLoader,DirectoryLoader,WebBaseLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_groq import ChatGroq
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_classic.chains import create_retrieval_chain
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.vectorstores import faiss
import tempfile


from pydantic import WebsocketUrl
def loader_pdf(file_path):
  loader=PyPDFLoader(file_path)
  documents=loader.load()
  return documents
def loader_csv(file_patb):
  csv_loaders=CSVLoader(file_path)
  documents=csv_loaders.load()
  return documents
def loader_web(file_path):
  web_loaders=WebBaseLoader(file_path)
  documents=web_loaders.loader()
  return documents
def loader_text(file_path):
  docs_loaders=Docx2txtLoader(file_path)
  documents=docs_loaders.load()
  return documents
def save_upload_file(upload_file):
  suffix=os.path.splitext(upload_file.name)[1]
  with tempfile.NamedTemporaryFile(delete=False,suffix=suffix) as temp_file:
    temp_file.write(upload_file.getvalue())
    return temp_file.name
def split_documents(documents):
  splitter=RecursiveCharacterTextSplitter(
      chunk_size=1000,
      chunk_overlap=200
  )
  chunks=splitter.split_documents(documents)
  return chunks
@st.cache_resource
def create_embeddings():
  embedding=HuggingFaceEmbeddings(
      model_name="sentence-transformers/all-MiniLM-L6-v2"
  )
  return embedding
@st.cache_resource
def create_vectorstore(chunks,embeddings):
    vectore_store=faiss.from_documents(
      documents=chunks,embedding=embeddings
    )
    return vectore_store
@st.cache_resource
def create_retriever(vector_store):
  retriever=vector_store.as_retriever(
      search_type="similarity",
      search_kwargs={"k":3}
  )
  return retriever
@st.cache_resource
def load_llm():
  llm=ChatGroq(
      model="llama-3.3-70b-versatile",
      temperature=0.5,
      api_key=os.getenv("GROQ_API_KEY")
  )
  return llm
def create_prompt():
  prompt=ChatPromptTemplate.from_messages(
      [
          (
      "system",
            """You are an AI Research Assistant.

Answer ONLY from the provided context.

If the answer is not present in the context, say:
'I couldn't find the answer in the provided documents.'
"""
        ),
        (
            "human",
            "Context:\n{context}\n\nQuestion:\n{input}"
        )


  ])
def create_document_chain(llm,prompt):
  chain=create_stuff_documents_chain(
      llm=llm,
      prompt=prompt
  )
  return chain
def create_rag_chain(retriever,chain):
  rag_chain=create_retrieval_chain(
      retriever,
      chain
  )
  return rag_chain
def main():
  load_dotenv()
  st.set_page_config(page_title="Ai resarch assistant",page_icon=":book:")

  st.header("Ai resarch assistant")
  col1, col2 = st.columns([1, 1.3])

  with col1:
    st.subheader("📂 Upload Research Documents")
    st.write("""
    Upload one or more documents and click **Process Documents**.

    Supported formats:
    - 📄 PDF
    - 📊 CSV
    - 📝 DOCX

    After processing, ask questions in the chat.
    """)

  with col2:
    st.title("🤖 AI Research Assistant")

    st.markdown("""
### Features

✅ Multi PDF Support

✅ CSV Support

✅ DOCX Support

✅ AI Question Answering

✅ Source Document Citation

✅ FAISS Vector Database

✅ HuggingFace Embeddings

✅ Groq Llama 3.3 70B

---

**How it Works**

1. Upload Documents
2. Process Documents
3. Ask Questions
4. Get AI Generated Answers
5. View Source Documents

---
""")

st.info("💡 Tip: Upload multiple research papers for better answers.")
if "messages" not in st.session_state:
    st.session_state.messages=[]
    st.text_input("ask the question from pdf or websearch what ever you want research")
with st.sidebar:
  st.subheader("pdf or websearch")
  uploaded_pdf=st.file_uploader("upload your resarch_paper or docuement and click on the process button"
  ,type=["pdf"],accept_multiple_files=True)
  uploaded_csv=upload_csv=st.file_uploader("upload your csv resarch docuement click on the process button "
  ,type=["csv"],accept_multiple_files=True)
  uploaded_docx=upload_docs=st.file_uploader("upload your docs resarch docuement click on the process button "
  ,type=["docs"],accept_multiple_files=True)
  #website_url=upload_url=st.text_input("upload your Url for resarch docuement click on the process button "
  #,type=["url"])

  process=st.button("process button")
  if st.button("🗑️ Clear Chat"):
    st.session_state.messages = []
    st.rerun()
  st.spinner("processing")
  if process:
    all_documents=[]
    if uploaded_pdf:
      for pdf in uploaded_pdf:
        temp_path=save_upload_file(pdf)
        docs=loader_pdf(temp_path)
        all_documents.extend(docs)
    if uploaded_csv:
      temp_path=save_upload_file(upload_csv)
      docs=loader_csv(temp_path)
      all_documents.extend(docs)
    if uploaded_docx:
      temp_path=save_upload_file(uploaded_docx)
      docs=loader_text(temp_path)
      all_documents.extend(docs)
    #if website_url:
     # docs=loader_web(website_url)
      all_documents.extend(docs)
      chunks=split_documents(all_documents)
      embeddings=create_embeddings()
      vectore_store=faiss.from_documents(
          chunks,
          embeddings
      )
      retriever=create_retriever(vector_store)
      llm=load_llm()
      prompt=create_prompt()
      chain=create_document_chain(
          llm,
          prompt
      )

      rag_chain=create_rag_chain(
          retriever,
          chains
      )
      st.session_state.rag_chain=rag_chain
      st.success("Research documents processed successfully!")
      for message in st.session_state.messages:
        with st.chat_message(message["role"]):
          st.markdown(message["content"])
      query=st.chat_input("ask your research quedtion")
      if query:
        st.session_state.messages.append(
              {
                      "role": "user",
                      "content": query
                                  }
                                  )

      with st.chat_message("user"):
         st.markdown(query)
      try:
         with st.spinner("thinking..."):
          response=st.session_state.rag_chain.invoke({"question":query})
          st.write("### answerr")
          st.write(response["answer"])
          with st.expander("view source document"):
            for i , doc in enumerate(response["context"],start=1):
              st.markdown(f"### source{i}")
              st.write(doc.page_content)
              st.divider()

      except Exception as e:
        st.error(f"error{e}")

      st.success("Chunking completed successfully")
      st.write("total documents:",len(all_documents))
      st.write("total chunks:",len(chunks))
  #pdf_documents=loader_pdf(file_path)
  #csv_documents=loader_csv(file_path)
  #web_documents=loader_web(file_path)
  #docs_documents=loader_docs(file_path)

if __name__ == "__main__":
    main()

